name: Tweet via bot.py

on: push
  # trigger every hour
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  build:
    name: Tweet via bot.py
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Tweet
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      run: |
        pip install -r requirements.txt
        python bot.py
